platform:
  - x64

cache:
  - '%LOCALAPPDATA%\electron\Cache'
  - node_modules -> package.json

install:
  - shorten_win_path.bat
  - set PATH=C:\Ruby23-x64\bin;%PATH%
  - path
  - echo "%cd%"
  - ps: Install-Product node 6 x64
  - yarn install

build_script:
  - yarn run icon-gen
  - path
  - echo "%cd%"
  - set PATH=C:\Ruby23-x64\bin;C:\Perl\site\bin;C:\Perl\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\7-Zip;C:\Tools\GitVersion;C:\Tools\PsTools;C:\Program Files\Git LFS;C:\Tools\WebDriver;C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\PrivateAssemblies\;C:\Ruby193\bin;C:\Tools\NUnit\bin;C:\Tools\xUnit;C:\Tools\MSpec;C:\Tools\Coverity\bin;C:\Program Files (x86)\CMake\bin;C:\go\bin;C:\Program Files\Java\jdk1.8.0\bin;C:\Python27;C:\Program Files\nodejs;C:\Program Files (x86)\iojs;C:\Program Files\iojs;C:\Users\appveyor\AppData\Roaming\npm;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\MSBuild\14.0\Bin;C:\Tools\NuGet;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Python27\Scripts;C:\Tools\NUnit3;C:\Program Files\LLVM\bin;C:\Tools\curl\bin;C:\Program Files\Amazon\AWSCLI\;C:\Program Files\Git\cmd;C:\Program Files\Git\usr\bin;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\140;C:\ProgramData\chocolatey\bin;C:\Program Files (x86)\nodejs\;C:\Program Files (x86)\Yarn\bin;C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code;C:\Program Files\Microsoft SDKs\Service Fabric\Tools\ServiceFabricLocalClusterManager;C:\Users\appveyor\AppData\Roaming\npm;C:\Users\appveyor\AppData\Local\Yarn\bin;C:\Program Files\AppVeyor\BuildAgent
  - node_modules\.bin\grunt
  - node_modules\.bin\build --em.environment=%SIGNAL_ENV% --publish=never

test_script:
  - node_modules\.bin\grunt test-release:win
  - node_modules\.bin\grunt test

artifacts:
  - path: dist/*.*

environment:
  SIGNAL_ENV: production

deploy:
  provider: Environment
  name: signal-desktop-builds
